services:
  - type: web
    name: discord-bot
    env: node
    buildCommand: npm install && apt-get update && apt-get install -y python3 python3-pip ffmpeg && pip3 install yt-dlp
    startCommand: node index.js
